#!/usr/bin/perl

print "Content-type: text/html\n\n";

$url = @ENV{'REQUEST_URI'};
$http_host = @ENV{'HTTP_HOST'};
$s_signature = @ENV{'SERVER_SIGNATURE'};
$s_name = @ENV{'SERVER_NAME'};
$lang = @ENV{'HTTP_ACCEPT_LANGUAGE'};



print "<html>\n";
print "<head>\n";
print "<meta http-equiv=\"Content-Type\" content=\"text/html;\">\n";
print "<title>Error 403 - Forbidden</title>\n";
print "</head>\n";
print "<body bgcolor=\"#FFFFFF\">\n";
if ( $lang eq "ru") {
    print "<h1>Доступ запрещен</h1>\n";
    print "Вы не имеете разрешения на доступ к $url на этом сервере.\n";
    } else {
    print "<h1>Forbidden</h1>\n";
    print "You don't have permission to access $url on this server.\n";
    }
print "<hr>\n";
print "$s_signature\n";
print "<IMG SRC=\"http://www.ruyan.ru/apache_pb.gif\" ALT=\"Apache\">";
print "</body>\n";
print "</html>\n";
